import {sample,validateQuiz,score} from './quiz.js';
const app=document.querySelector('#app');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let quizzes=[structuredClone(sample)],completed=0,storageWarning='';
try{const saved=localStorage.getItem('quiz-estudo-v1');if(saved){const parsed=JSON.parse(saved);if(!Array.isArray(parsed)||!parsed.every(validateQuiz))throw Error();quizzes=parsed;}completed=Number(localStorage.getItem('quiz-estudo-completed'))||0;}catch{storageWarning='Não foi possível ler os dados locais. Você pode usar o app e exportar seus quizzes para guardá-los.';}
function save(){try{localStorage.setItem('quiz-estudo-v1',JSON.stringify(quizzes));localStorage.setItem('quiz-estudo-completed',String(completed));return true;}catch{storageWarning='O navegador não permitiu salvar. Exporte seus quizzes antes de fechar esta página.';return false;}}
const back=()=>'<button class="secondary back" id="back">← Meus quizzes</button>';
function home(){app.innerHTML=`<section class="hero"><div><div class="eyebrow">Aprenda no seu ritmo</div><h1>Transforme perguntas<br>em conhecimento.</h1><p>Crie seus próprios quizzes, coloque o que aprendeu em prática e descubra onde pode melhorar.</p><button id="create">＋ Criar um quiz</button></div><div class="illustration"><div class="symbol">✦</div><strong>Um pouco todo dia.<br>Um passo mais longe.</strong><p>Seu próximo aprendizado começa aqui.</p></div></section><div class="stats"><div><strong>${quizzes.length}</strong><span>Quizzes disponíveis</span></div><div><strong>${quizzes.reduce((n,q)=>n+q.questions.length,0)}</strong><span>Questões para estudar</span></div><div><strong>${completed}</strong><span>Práticas concluídas</span></div></div><div class="section-top"><h2>Sua biblioteca</h2><div class="actions" style="margin:0"><button class="secondary" id="import">Importar</button><button class="secondary" id="export">Exportar</button></div></div><p class="hint">Seus quizzes ficam neste navegador. Exporte uma cópia para guardar ou estudar em outro dispositivo.</p>${storageWarning?`<div class="notice" role="status">${escape(storageWarning)}</div>`:''}<div class="grid">${quizzes.map((q,i)=>`<article class="card"><span class="badge">${escape(q.subject||'Meus estudos')}</span><h3>${escape(q.title)}</h3><p>${q.questions.length} questões · Múltipla escolha</p><button data-play="${i}">Começar a estudar →</button><div class="actions"><button class="secondary" data-edit="${i}">Editar</button><button class="danger" data-delete="${i}">Excluir</button></div></article>`).join('')||'<div class="panel"><h3>Seu primeiro quiz espera por você</h3><p>Clique em “Criar um quiz” para adicionar suas questões.</p></div>'}</div><input type="file" id="file" accept="application/json,.json" hidden>`;
 document.querySelector('#create').onclick=()=>editor();
 app.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(quizzes[Number(b.dataset.play)]));
 app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editor(Number(b.dataset.edit)));
 app.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.delete);if(confirm(`Excluir “${quizzes[i].title}”?`)){quizzes.splice(i,1);save();home();}});
 document.querySelector('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(quizzes,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='meus-quizzes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 document.querySelector('#import').onclick=()=>document.querySelector('#file').click();
 document.querySelector('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Arquivo maior que 2 MB.');const items=JSON.parse(await file.text());if(!Array.isArray(items)||!items.length||!items.every(validateQuiz))throw Error('O arquivo deve conter uma lista de quizzes válidos com quatro alternativas por questão.');quizzes.push(...items.map(q=>({...q,id:crypto.randomUUID()})));save();home();}catch(err){alert('Não foi possível importar: '+err.message);}};
}
function editor(index){const draft=index===undefined?{title:'',subject:'',questions:[{prompt:'',options:['','','',''],answer:0,explanation:''}]}:structuredClone(quizzes[index]);
 const render=()=>{app.innerHTML=`<div class="narrow">${back()}<div class="eyebrow">Crie para aprender</div><h1>${index===undefined?'Novo quiz':'Editar quiz'}</h1><p>Escreva suas perguntas e marque a alternativa correta.</p><form id="editor" class="panel"><label for="title">Nome do quiz</label><input id="title" required maxlength="120" value="${escape(draft.title)}" placeholder="Ex.: Biologia — células"><label for="subject">Matéria ou tema</label><input id="subject" maxlength="80" value="${escape(draft.subject)}" placeholder="Ex.: Biologia">${draft.questions.map((q,i)=>`<section class="question-editor"><div class="section-top"><h3>Questão ${i+1}</h3>${draft.questions.length>1?`<button type="button" class="danger" data-remove="${i}">Remover</button>`:''}</div><label for="prompt-${i}">Pergunta</label><textarea id="prompt-${i}" required maxlength="2000">${escape(q.prompt)}</textarea><p class="hint">Selecione o círculo ao lado da resposta correta.</p>${q.options.map((o,j)=>`<div class="option-row"><input aria-label="Alternativa ${j+1} é a correta da questão ${i+1}" type="radio" name="answer-${i}" value="${j}" ${q.answer===j?'checked':''}><label><span class="hint">Alternativa ${j+1}</span><input id="option-${i}-${j}" required maxlength="500" value="${escape(o)}"></label></div>`).join('')}<label for="explanation-${i}">Explicação (opcional)</label><textarea id="explanation-${i}" maxlength="2000" placeholder="Explique por que essa resposta está correta.">${escape(q.explanation)}</textarea></section>`).join('')}<div class="actions"><button class="secondary" type="button" id="add">＋ Adicionar questão</button><button type="submit">Salvar quiz</button></div><p class="error" id="error" role="alert"></p></form></div>`;
 const collect=()=>{draft.title=document.querySelector('#title').value.trim();draft.subject=document.querySelector('#subject').value.trim();draft.questions=draft.questions.map((q,i)=>({prompt:document.querySelector(`#prompt-${i}`).value.trim(),options:q.options.map((_,j)=>document.querySelector(`#option-${i}-${j}`).value.trim()),answer:Number(document.querySelector(`input[name="answer-${i}"]:checked`).value),explanation:document.querySelector(`#explanation-${i}`).value.trim()}));};
 document.querySelector('#back').onclick=()=>{if(confirm('Sair sem salvar as alterações?'))home();};
 document.querySelector('#add').onclick=()=>{collect();draft.questions.push({prompt:'',options:['','','',''],answer:0,explanation:''});render();};
 app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{collect();draft.questions.splice(Number(b.dataset.remove),1);render();});
 document.querySelector('#editor').onsubmit=e=>{e.preventDefault();collect();if(!validateQuiz(draft)){document.querySelector('#error').textContent='Preencha o nome, as perguntas e todas as alternativas.';return;}draft.id=draft.id||crypto.randomUUID();if(index===undefined)quizzes.push(draft);else quizzes[index]=draft;save();home();};
 };render();}
function play(quiz){let current=0,selected=null,revealed=false;const answers=[];
 const render=()=>{const q=quiz.questions[current];app.innerHTML=`<div class="narrow">${back()}<div class="eyebrow">${escape(quiz.subject||'Hora de praticar')}</div><h1>${escape(quiz.title)}</h1><p>Questão ${current+1} de ${quiz.questions.length}</p><div class="progress" role="progressbar" aria-label="Progresso do quiz" aria-valuenow="${current}" aria-valuemin="0" aria-valuemax="${quiz.questions.length}"><div style="width:${current/quiz.questions.length*100}%"></div></div><div class="panel"><h2>${escape(q.prompt)}</h2><div class="choices">${q.options.map((o,j)=>`<button class="choice ${selected===j?'selected':''} ${revealed&&j===q.answer?'correct':''} ${revealed&&selected===j&&j!==q.answer?'wrong':''}" data-choice="${j}" aria-pressed="${selected===j}" ${revealed?'disabled':''}><span class="letter">${'ABCD'[j]}</span>${escape(o)}</button>`).join('')}</div>${revealed?`<div class="feedback" role="status"><strong>${selected===q.answer?'✓ Você acertou!':'Vamos aprender com essa.'}</strong><br>Resposta correta: ${escape(q.options[q.answer])}${q.explanation?`<br>${escape(q.explanation)}`:''}</div>`:''}<div class="actions"><button id="next" ${selected===null?'disabled':''}>${revealed?(current===quiz.questions.length-1?'Ver resultado':'Próxima questão →'):'Confirmar resposta'}</button></div></div></div>`;
 document.querySelector('#back').onclick=()=>{if(confirm('Encerrar esta prática? Seu resultado parcial não será contado.'))home();};
 app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.choice);render();});
 document.querySelector('#next').onclick=()=>{if(!revealed){answers[current]=selected;revealed=true;render();}else if(current<quiz.questions.length-1){current++;selected=null;revealed=false;render();}else{completed++;save();result();}};
 };
 const result=()=>{const correct=score(quiz.questions,answers);app.innerHTML=`<div class="narrow">${back()}<div class="panel result"><div class="eyebrow">Prática concluída</div><h1>Mais um passo no aprendizado.</h1><div class="score">${Math.round(correct/quiz.questions.length*100)}%</div><p>Você acertou ${correct} de ${quiz.questions.length} questões.</p><button id="again">Praticar novamente</button><h2 style="margin-top:35px">Revise suas respostas</h2>${quiz.questions.map((q,i)=>`<div class="question-editor review"><strong>${answers[i]===q.answer?'✓':'✕'} ${escape(q.prompt)}</strong><p>Sua resposta: ${escape(q.options[answers[i]])}</p>${answers[i]!==q.answer?`<p>Resposta correta: ${escape(q.options[q.answer])}</p>`:''}${q.explanation?`<p>${escape(q.explanation)}</p>`:''}</div>`).join('')}</div></div>`;document.querySelector('#back').onclick=home;document.querySelector('#again').onclick=()=>play(quiz);};render();}
home();
